import Footer from '@/components/Footer';
import Header from '@/components/Header';
import type { Metadata } from 'next';
import './globals.css';
import '@/components/header.css';
import '@/components/sidebar.css';

export const metadata: Metadata = {
  title: 'M. Aktaruzzman Opu',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-black relative pb-20 pt-24 min-h-screen">
        <Header />
        <div className="w-[55%] max-w-[850px] mx-auto">{children}</div>
        <footer>
          <Footer />
        </footer>
      </body>
    </html>
  );
}
